# Generated by Django 4.2.16 on 2024-10-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyOfWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('info_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishStocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocking_date', models.DateField()),
                ('species', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('source_url', models.URLField()),
                ('body_of_water', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockings', to='stockings.bodyofwater')),
            ],
        ),
    ]
